[package]
name = "light-client"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy.workspace = true
alloy-provider.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
celestia-rpc.workspace = true
celestia-types.workspace = true
ev-prover.workspace = true
ev-batch-program.workspace = true
ev-types.workspace = true
ev-zkevm-types.workspace = true
prost.workspace = true
celestia-grpc-client.workspace = true
bincode.workspace = true
serde_cbor.workspace = true
tendermint-light-client-verifier.workspace = true
reth-chainspec.workspace = true
reth-primitives.workspace = true
tendermint-rpc.workspace = true
rustls.workspace = true
url.workspace = true
tokio.workspace = true
dstack-verifier.workspace = true
hex.workspace = true
serde_json.workspace = true
serde.workspace = true
dcap-qvl.workspace = true
sp1-sdk.workspace = true
types.workspace = true
rsp-client-executor.workspace = true
rsp-host-executor.workspace = true
rsp-primitives.workspace = true
rsp-rpc-db.workspace = true

[build-dependencies]
sp1-build.workspace = true
