[workspace]
members = ["app", "circuit", "light-client", "types"]
resolver = "2"

[workspace.dependencies]
alloy = { version = "=1.0.32", default-features = false, features = ["serde"] }
alloy-consensus = { version = "=1.0.41", default-features = false, features = [
    "std",
    "serde",
] }
alloy-genesis = { version = "=1.0.32", default-features = false }
alloy-primitives = { version = "=1.3.0", default-features = false }
alloy-provider = { version = "=1.0.32", default-features = false, features = [
    "ws",
    "reqwest",
    "reqwest-rustls-tls",
] }
alloy-rlp = { version = "=0.3.12", default-features = false }
alloy-rpc-types = { version = "=1.0.32", default-features = false }
alloy-sol-types = "=1.3"
alloy-trie = { version = "=0.9.1", default-features = false }
anyhow = "1.0"
axum = "0.8"
dcap-qvl = { git = "https://github.com/jonas089/dcap-qvl", default-features = false, features = [
    "std",
], branch = "v0.3.4-zk" }
celestia-rpc = "=0.13.0"
celestia-types = "=0.15.0"

ev-prover = { git = "https://github.com/celestiaorg/celestia-zkevm" }
ev-batch-program = { git = "https://github.com/celestiaorg/celestia-zkevm" }
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp.git", tag = "reth-1.5.0" }
rsp-host-executor = { git = "https://github.com/succinctlabs/rsp.git", tag = "reth-1.5.0" }
rsp-primitives = { git = "https://github.com/succinctlabs/rsp.git", tag = "reth-1.5.0" }
rsp-rpc-db = { git = "https://github.com/succinctlabs/rsp.git", tag = "reth-1.5.0" }

dotenvy = "0.15.7"
rustls = { version = "0.23", features = ["aws_lc_rs"] }
# dstack dependencies
dstack-sdk = { git = "https://github.com/jonas089/dstack", default-features = false }
dstack-types = { git = "https://github.com/jonas089/dstack", default-features = false }
dstack-verifier = { git = "https://github.com/jonas089/dstack", default-features = false }
ev-types = { version = "0.0.1", default-features = false }
ev-zkevm-types = { git = "https://github.com/celestiaorg/celestia-zkevm/", branch = "jonas/celestia-root-verification" }
tendermint-rpc = { version = "0.40.1", features = ["http-client"] }
celestia-grpc-client = { git = "https://github.com/celestiaorg/celestia-zkevm/" }
hex = "0.4"
light-client = { path = "light-client" }
prost = "0.12"
bincode = "1.3.3"
# reth and rsp dependencies
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0", default-features = false }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11.2"
serde_json = "1.0"
sha2 = "0.10.9"
tendermint-light-client-verifier = { version = "0.40.1", default-features = false, features = [
    "rust-crypto",
] }
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.2"

sp1-build = "=5.2.2"
sp1-core-executor = { version = "=5.2.2", features = ["bigint-rug"] }
sp1-primitives = "=5.2.2"
sp1-prover = "=5.2.2"
sp1-sdk = { version = "=5.2.2", features = ["native-gnark"] }
sp1-zkvm = "=5.2.2"
types = { path = "types" }

[patch.crates-io]
# Add support for precompiles: https://docs.succinct.xyz/docs/sp1/optimizing-programs/precompiles
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", tag = "patch-sha2-0.10.9-sp1-4.0.0", package = "sha2" }
bn = { git = "https://github.com/sp1-patches/bn", tag = "patch-0.6.0-sp1-5.0.0", package = "substrate-bn" }
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", tag = "patch-sha3-0.10.8-sp1-4.0.0" }
k256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-k256-13.4-sp1-5.0.0" }
p256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-p256-13.2-sp1-5.0.0" }
curve25519-dalek = { git = "https://github.com/sp1-patches/curve25519-dalek", tag = "patch-4.1.3-sp1-5.0.0" }
