[package]
name = "evolve-tee"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axum.workspace = true
dstack-sdk.workspace = true
dstack-types.workspace = true
dstack-verifier.workspace = true
hex.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
