[package]
name = "middleware"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "middleware"
path = "src/bin/middleware.rs"

[dependencies]
alloy.workspace = true
anyhow.workspace = true
axum.workspace = true
bincode.workspace = true
celestia-grpc-client.workspace = true
celestia-rpc.workspace = true
dotenvy.workspace = true
ev-prover.workspace = true
ev-zkevm-types.workspace = true
futures.workspace = true
hex.workspace = true
light-client.workspace = true
serde.workspace = true
serde_json.workspace = true
tendermint-rpc.workspace = true
tokio.workspace = true
rustls.workspace = true
